In [ ]:
import pandas as pd

In [ ]:
pd.read_csv("movies.csv")

Rank                         Title           Studio       Gross  Year
0       1             Avengers: Endgame      Buena Vista  $2,796.30   2019
1       2                        Avatar              Fox  $2,789.70   2009
2       3                       Titanic        Paramount  $2,187.50   1997
3       4  Star Wars: The Force Awakens      Buena Vista  $2,068.20   2015
4       5        Avengers: Infinity War      Buena Vista  $2,048.40   2018
..    ...                           ...              ...         ...   ...
777   778                     Yogi Bear  Warner Brothers    $201.60   2010
778   779           Garfield: The Movie              Fox    $200.80   2004
779   780                   Cats & Dogs  Warner Brothers    $200.70   2001
780   781      The Hunt for Red October        Paramount    $200.50   1990
781   782                      Valkyrie              MGM    $200.30   2008

[782 rows x 5 columns]

In [ ]:
pd.read_csv("movies.csv", index_col="Title" )

Rank           Studio       Gross  Year
Title                                                                
Avengers: Endgame                1      Buena Vista  $2,796.30   2019
Avatar                           2              Fox  $2,789.70   2009
Titanic                          3        Paramount  $2,187.50   1997
Star Wars: The Force Awakens     4      Buena Vista  $2,068.20   2015
Avengers: Infinity War           5      Buena Vista  $2,048.40   2018
...                            ...              ...         ...   ...
Yogi Bear                      778  Warner Brothers    $201.60   2010
Garfield: The Movie            779              Fox    $200.80   2004
Cats & Dogs                    780  Warner Brothers    $200.70   2001
The Hunt for Red October       781        Paramount    $200.50   1990
Valkyrie                       782              MGM    $200.30   2008

[782 rows x 4 columns]

In [ ]:
movies = pd.read_csv("movies.csv", index_col="Title" )

In [ ]:
movies.head(n=3)

Rank       Studio       Gross  Year
Title                                                 
Avengers: Endgame     1  Buena Vista  $2,796.30   2019
Avatar                2          Fox  $2,789.70   2009
Titanic               3    Paramount  $2,187.50   1997

In [ ]:
movies.tail(n=3)

Rank           Studio     Gross  Year
Title                                                          
Cats & Dogs                780  Warner Brothers  $200.70   2001
The Hunt for Red October   781        Paramount  $200.50   1990
Valkyrie                   782              MGM  $200.30   2008

In [ ]:
movies.shape

(782, 4)

In [ ]:
movies.size

3128

In [ ]:
movies.iloc[2]

Rank               3
Studio     Paramount
Gross     $2,187.50 
Year            1997
Name: Titanic, dtype: object

In [ ]:
movies.loc["Cats & Dogs"]

Rank                  780
Studio    Warner Brothers
Gross            $200.70 
Year                 2001
Name: Cats & Dogs, dtype: object

In [ ]:
movies.sort_values(by="Year", ascending=False)

Rank                  Studio  \
Title                                                                      
Avengers: Endgame                              1             Buena Vista   
John Wick: Chapter 3 - Parabellum            458               Lionsgate   
The Wandering Earth                          114  China Film Corporation   
Toy Story 4                                  198             Buena Vista   
How to Train Your Dragon: The Hidden World   199               Universal   
...                                          ...                     ...   
The Godfather                                604               Paramount   
The Jungle Book                              755             Buena Vista   
101 Dalmatians                               708             Buena Vista   
Bambi                                        540                     RKO   
Gone with the Wind                           288                     MGM   

                                                 Gross  Year  
Title                                                         
Avengers: Endgame                           $2,796.30   2019  
John Wick: Chapter 3 - Parabellum             $304.70   2019  
The Wandering Earth                           $699.80   2019  
Toy Story 4                                   $519.80   2019  
How to Train Your Dragon: The Hidden World    $519.80   2019  
...                                                ...   ...  
The Godfather                                 $245.10   1972  
The Jungle Book                               $205.80   1967  
101 Dalmatians                                $215.90   1961  
Bambi                                         $267.40   1942  
Gone with the Wind                            $402.40   1939  

[782 rows x 4 columns]

In [ ]:
movies.sort_values(by="Year", ascending=False).head()

Rank                  Studio  \
Title                                                                      
Avengers: Endgame                              1             Buena Vista   
John Wick: Chapter 3 - Parabellum            458               Lionsgate   
The Wandering Earth                          114  China Film Corporation   
Toy Story 4                                  198             Buena Vista   
How to Train Your Dragon: The Hidden World   199               Universal   

                                                 Gross  Year  
Title                                                         
Avengers: Endgame                           $2,796.30   2019  
John Wick: Chapter 3 - Parabellum             $304.70   2019  
The Wandering Earth                           $699.80   2019  
Toy Story 4                                   $519.80   2019  
How to Train Your Dragon: The Hidden World    $519.80   2019

In [ ]:
movies.sort_index().head()

Rank           Studio     Gross  Year
Title                                                  
10,000 B.C.        536  Warner Brothers  $269.80   2008
101 Dalmatians     708      Buena Vista  $215.90   1961
101 Dalmatians     425      Buena Vista  $320.70   1996
2 Fast 2 Furious   632        Universal  $236.40   2003
2012                93             Sony  $769.70   2009

In [ ]:
movies["Studio"]

Title
Avengers: Endgame                   Buena Vista
Avatar                                      Fox
Titanic                               Paramount
Star Wars: The Force Awakens        Buena Vista
Avengers: Infinity War              Buena Vista
                                     ...       
Yogi Bear                       Warner Brothers
Garfield: The Movie                         Fox
Cats & Dogs                     Warner Brothers
The Hunt for Red October              Paramount
Valkyrie                                    MGM
Name: Studio, Length: 782, dtype: object

In [ ]:
movies[["Studio","Year"]]

Studio  Year
Title                                              
Avengers: Endgame                 Buena Vista  2019
Avatar                                    Fox  2009
Titanic                             Paramount  1997
Star Wars: The Force Awakens      Buena Vista  2015
Avengers: Infinity War            Buena Vista  2018
...                                       ...   ...
Yogi Bear                     Warner Brothers  2010
Garfield: The Movie                       Fox  2004
Cats & Dogs                   Warner Brothers  2001
The Hunt for Red October            Paramount  1990
Valkyrie                                  MGM  2008

[782 rows x 2 columns]

In [ ]:
movies["Studio"].value_counts().head(10)

Warner Brothers    132
Buena Vista        125
Fox                117
Universal          109
Sony                86
Paramount           76
Dreamworks          27
Lionsgate           21
New Line            16
MGM                 11
Name: Studio, dtype: int64

In [ ]:
movies["Studio"] == "Universal"

Title
Avengers: Endgame               False
Avatar                          False
Titanic                         False
Star Wars: The Force Awakens    False
Avengers: Infinity War          False
                                ...  
Yogi Bear                       False
Garfield: The Movie             False
Cats & Dogs                     False
The Hunt for Red October        False
Valkyrie                        False
Name: Studio, Length: 782, dtype: bool

In [ ]:
movies[movies["Studio"] == "Universal"]

Rank     Studio       Gross  Year
Title                                                            
Jurassic World                     6  Universal  $1,671.70   2015
Furious 7                          8  Universal  $1,516.00   2015
Jurassic World: Fallen Kingdom    13  Universal  $1,309.50   2018
The Fate of the Furious           17  Universal  $1,236.00   2017
Minions                           19  Universal  $1,159.40   2015
...                              ...        ...         ...   ...
The Break-Up                     763  Universal    $205.00   2006
Everest                          766  Universal    $203.40   2015
Patch Adams                      772  Universal    $202.30   1998
Kindergarten Cop                 775  Universal    $202.00   1990
Straight Outta Compton           776  Universal    $201.60   2015

[109 rows x 4 columns]

In [ ]:
release_by_universal = movies["Studio"] == "Universal"
release_by_universal

Title
Avengers: Endgame               False
Avatar                          False
Titanic                         False
Star Wars: The Force Awakens    False
Avengers: Infinity War          False
                                ...  
Yogi Bear                       False
Garfield: The Movie             False
Cats & Dogs                     False
The Hunt for Red October        False
Valkyrie                        False
Name: Studio, Length: 782, dtype: bool

In [ ]:
movies[release_by_universal].head()

Rank     Studio       Gross  Year
Title                                                            
Jurassic World                     6  Universal  $1,671.70   2015
Furious 7                          8  Universal  $1,516.00   2015
Jurassic World: Fallen Kingdom    13  Universal  $1,309.50   2018
The Fate of the Furious           17  Universal  $1,236.00   2017
Minions                           19  Universal  $1,159.40   2015

In [ ]:
release_by_universal = movies["Studio"] == "Universal"
release_in_2015 = movies["Year"] == 2015

In [ ]:
movies[release_by_universal & release_in_2015]

Rank     Studio       Gross  Year
Title                                                    
Jurassic World             6  Universal  $1,671.70   2015
Furious 7                  8  Universal  $1,516.00   2015
Minions                   19  Universal  $1,159.40   2015
Fifty Shades of Grey     165  Universal    $571.00   2015
Pitch Perfect 2          504  Universal    $287.50   2015
Ted 2                    702  Universal    $216.70   2015
Everest                  766  Universal    $203.40   2015
Straight Outta Compton   776  Universal    $201.60   2015

In [ ]:
movies[release_by_universal | release_in_2015]

Rank       Studio       Gross  Year
Title                                                              
Star Wars: The Force Awakens       4  Buena Vista  $2,068.20   2015
Jurassic World                     6    Universal  $1,671.70   2015
Furious 7                          8    Universal  $1,516.00   2015
Avengers: Age of Ultron            9  Buena Vista  $1,405.40   2015
Jurassic World: Fallen Kingdom    13    Universal  $1,309.50   2018
...                              ...          ...         ...   ...
The Break-Up                     763    Universal    $205.00   2006
Everest                          766    Universal    $203.40   2015
Patch Adams                      772    Universal    $202.30   1998
Kindergarten Cop                 775    Universal    $202.00   1990
Straight Outta Compton           776    Universal    $201.60   2015

[140 rows x 4 columns]

In [ ]:
before_1975 = movies["Year"] < 1975

In [ ]:
movies[before_1975]

Rank           Studio     Gross  Year
Title                                                    
The Exorcist         252  Warner Brothers  $441.30   1973
Gone with the Wind   288              MGM  $402.40   1939
Bambi                540              RKO  $267.40   1942
The Godfather        604        Paramount  $245.10   1972
101 Dalmatians       708      Buena Vista  $215.90   1961
The Jungle Book      755      Buena Vista  $205.80   1967

In [ ]:
before_1986 = movies["Year"] <= 1986
after_1983 = movies["Year"] >= 1983

In [ ]:
movies[after_1983 & before_1986]

Rank     Studio     Gross  Year
Title                                                                
Return of the Jedi                     222        Fox  $475.10   1983
Back to the Future                     311  Universal  $381.10   1985
Top Gun                                357  Paramount  $356.80   1986
Indiana Jones and the Temple of Doom   403  Paramount  $333.10   1984
Crocodile Dundee                       413  Paramount  $328.20   1986
Beverly Hills Cop                      432  Paramount  $316.40   1984
Rocky IV                               467        MGM  $300.50   1985
Rambo: First Blood Part II             469    TriStar  $300.40   1985
Ghostbusters                           485   Columbia  $295.20   1984
Out of Africa                          662  Universal  $227.50   1985

In [ ]:
mid_80s = movies["Year"].between(1983,1986)

In [ ]:
movies[mid_80s]

Rank     Studio     Gross  Year
Title                                                                
Return of the Jedi                     222        Fox  $475.10   1983
Back to the Future                     311  Universal  $381.10   1985
Top Gun                                357  Paramount  $356.80   1986
Indiana Jones and the Temple of Doom   403  Paramount  $333.10   1984
Crocodile Dundee                       413  Paramount  $328.20   1986
Beverly Hills Cop                      432  Paramount  $316.40   1984
Rocky IV                               467        MGM  $300.50   1985
Rambo: First Blood Part II             469    TriStar  $300.40   1985
Ghostbusters                           485   Columbia  $295.20   1984
Out of Africa                          662  Universal  $227.50   1985

In [ ]:
has_dark_in_title = movies.index.str.lower().str.contains("dark")

In [ ]:
movies[has_dark_in_title]

Rank           Studio       Gross  Year
Title                                                                  
Transformers: Dark of the Moon    23        Paramount  $1,123.80   2011
The Dark Knight Rises             27  Warner Brothers  $1,084.90   2012
The Dark Knight                   39  Warner Brothers  $1,004.90   2008
Thor: The Dark World             132      Buena Vista    $644.60   2013
Star Trek Into Darkness          232        Paramount    $467.40   2013
Fifty Shades Darker              309        Universal    $381.50   2017
Dark Shadows                     600  Warner Brothers    $245.50   2012
Dark Phoenix                     603              Fox    $245.10   2019

In [ ]:
movies["Gross"].str.replace("$","",regex=False).str.replace(",","",regex=False).astype(float)

Title
Avengers: Endgame               2796.3
Avatar                          2789.7
Titanic                         2187.5
Star Wars: The Force Awakens    2068.2
Avengers: Infinity War          2048.4
                                 ...  
Yogi Bear                        201.6
Garfield: The Movie              200.8
Cats & Dogs                      200.7
The Hunt for Red October         200.5
Valkyrie                         200.3
Name: Gross, Length: 782, dtype: float64

In [ ]:
# sobreescribir una coluna, transformación de texto a flotante
movies["Gross"] = (
    movies["Gross"]
    .str.replace("$","",regex=False)
    .str.replace(",","",regex=False)
    .astype(float)
)

In [ ]:
movies

Rank           Studio   Gross  Year
Title                                                            
Avengers: Endgame                1      Buena Vista  2796.3  2019
Avatar                           2              Fox  2789.7  2009
Titanic                          3        Paramount  2187.5  1997
Star Wars: The Force Awakens     4      Buena Vista  2068.2  2015
Avengers: Infinity War           5      Buena Vista  2048.4  2018
...                            ...              ...     ...   ...
Yogi Bear                      778  Warner Brothers   201.6  2010
Garfield: The Movie            779              Fox   200.8  2004
Cats & Dogs                    780  Warner Brothers   200.7  2001
The Hunt for Red October       781        Paramount   200.5  1990
Valkyrie                       782              MGM   200.3  2008

[782 rows x 4 columns]

In [ ]:
movies["Gross"].mean()

439.0308184143226

In [ ]:
#agrupación
studios = movies.groupby("Studio")

In [ ]:
studios

In [ ]:
studios["Gross"].count().sort_values(ascending=False).head()

Studio
Warner Brothers    132
Buena Vista        125
Fox                117
Universal          109
Sony                86
Name: Gross, dtype: int64

In [ ]:
studios["Gross"].mean().sort_values(ascending=False).head(4)

Studio
HC                        870.30
China Film Corporation    699.80
Newmarket                 611.90
Buena Vista               588.68
Name: Gross, dtype: float64

In [ ]:
studios["Gross"].sum().sort_values(ascending=False).head(4)

Studio
Buena Vista        73585.0
Warner Brothers    58643.8
Fox                50420.8
Universal          44302.3
Name: Gross, dtype: float64

# Series

In [ ]:
pd.Series()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  """Entry point for launching an IPython kernel.


Series([], dtype: float64)

In [ ]:
ice_cream_flavors = ["Chocolate","Vanilla","Strawberry","Rum Raisins"]

In [ ]:
pd.Series(ice_cream_flavors)

0      Chocolate
1        Vanilla
2     Strawberry
3    Rum Raisins
dtype: object

In [ ]:
days_of_week = ["Monday","Wednesday","Friday","Saturday"]

In [ ]:
pd.Series(ice_cream_flavors,days_of_week)

Monday         Chocolate
Wednesday        Vanilla
Friday        Strawberry
Saturday     Rum Raisins
dtype: object

In [ ]:
pd.Series(data = ice_cream_flavors, index = days_of_week)

Monday         Chocolate
Wednesday        Vanilla
Friday        Strawberry
Saturday     Rum Raisins
dtype: object

In [ ]:
pd.Series(data = ice_cream_flavors, index = days_of_week)[0]

'Chocolate'

In [ ]:
pd.Series(data = ice_cream_flavors, index = days_of_week)["Saturday"]

'Rum Raisins'

In [ ]:
bunch_of_bools = [True,False,True]
pd.Series(bunch_of_bools)

0     True
1    False
2     True
dtype: bool

In [ ]:
stock_prices = [985.32,950.44]
time_of_day = ["Open","Close"]
pd.Series(data=stock_prices, index=time_of_day)

Open     985.32
Close    950.44
dtype: float64

In [ ]:
lucky_numbers = [4,8,15,16,23,42]
pd.Series(lucky_numbers)

0     4
1     8
2    15
3    16
4    23
5    42
dtype: int64

In [ ]:
pd.Series(lucky_numbers, dtype="float")

0     4.0
1     8.0
2    15.0
3    16.0
4    23.0
5    42.0
dtype: float64

In [ ]:
import numpy as np

temperatures = [94, 88, np.nan, 91]

In [ ]:
pd.Series(temperatures)

0    94.0
1    88.0
2     NaN
3    91.0
dtype: float64

In [ ]:
calorie_info = {"Cereal":125,"Chocolate bar":406, "Ice Cream Sundae":342}
calorie_info

{'Cereal': 125, 'Chocolate bar': 406, 'Ice Cream Sundae': 342}

In [ ]:
diet = pd.Series(calorie_info)
diet

Cereal              125
Chocolate bar       406
Ice Cream Sundae    342
dtype: int64

In [ ]:
pd.Series(data=("Red","Green","Blue"))

0      Red
1    Green
2     Blue
dtype: object

In [ ]:
rgb_colors = [(74, 138, 91),(171, 84, 55),(50, 164, 179)]
rgb_colors

[(74, 138, 91), (171, 84, 55), (50, 164, 179)]

In [ ]:
pd.Series(rgb_colors)

0     (74, 138, 91)
1     (171, 84, 55)
2    (50, 164, 179)
dtype: object

In [ ]:
my_set = {"Ricky", "Bobby"}

In [ ]:
# pd.Series(my_set) # Esto lanza error TypeError: 'set' type is unordered

In [ ]:
pd.Series(list(my_set))

0    Bobby
1    Ricky
dtype: object

In [ ]:
random_data = np.random.randint(1,101,10)
random_data

array([20, 19, 34, 86, 98, 83, 13, 97, 65, 78])

In [ ]:
pd.Series(random_data)

0    20
1    19
2    34
3    86
4    98
5    83
6    13
7    97
8    65
9    78
dtype: int64

In [ ]:
# Un poco de Object Oriented Programming
class Bike:
  gear = 1
  speed = 0

  def __init__(self, gear,speed):
    self.gear = gear
    self.speed = speed

  def speedUp(self, increase):
    self.speed += increase

  def applyBrake(self, decrease):
    self.speed -= decrease

  def changeGear(self, new_gear):
    self.gear = new_gear

In [ ]:
una_bici = Bike(gear = 3, speed = 10)

In [ ]:
una_bici.gear

3

In [ ]:
una_bici.speed

10

In [ ]:
una_bici.changeGear(1)

In [ ]:
una_bici.gear

1

In [ ]:
calorie_info = {"Cereal":125,"Chocolate bar":406, "Ice Cream Sundae":342}
calorie_info
diet = pd.Series(calorie_info)
diet

Cereal              125
Chocolate bar       406
Ice Cream Sundae    342
dtype: int64

In [ ]:
diet.values

array([125, 406, 342])

In [ ]:
diet.index

Index(['Cereal', 'Chocolate bar', 'Ice Cream Sundae'], dtype='object')

In [ ]:
diet.dtype

dtype('int64')

In [ ]:
diet.size

3

In [ ]:
diet.shape

(3,)

In [ ]:
diet.is_unique

True

In [ ]:
pd.Series(data=[3,3]).is_unique

False

In [ ]:
pd.Series(data=[1,3,6]).is_monotonic

True

In [ ]:
pd.Series(data=[1,6,3]).is_monotonic

False

In [ ]:
values = range(0,500,5)
nums = pd.Series(data = values)
nums

0       0
1       5
2      10
3      15
4      20
     ... 
95    475
96    480
97    485
98    490
99    495
Length: 100, dtype: int64

In [ ]:
nums.head()

0     0
1     5
2    10
3    15
4    20
dtype: int64

In [ ]:
nums.tail()

95    475
96    480
97    485
98    490
99    495
dtype: int64

# Algunas operaciones matemáticas

In [ ]:
numbers = pd.Series([1,2,3,np.nan,4,5])
numbers

0    1.0
1    2.0
2    3.0
3    NaN
4    4.0
5    5.0
dtype: float64

In [ ]:
numbers.count()

5

In [ ]:
numbers.sum()

15.0

In [ ]:
numbers.sum(skipna=False)

nan

In [ ]:
numbers.sum().sum(min_count=3)

15.0

In [ ]:
numbers.product()

120.0

In [ ]:
numbers.cumsum()

0     1.0
1     3.0
2     6.0
3     NaN
4    10.0
5    15.0
dtype: float64

In [ ]:
numbers.cumsum(skipna=False)

0    1.0
1    3.0
2    6.0
3    NaN
4    NaN
5    NaN
dtype: float64

In [ ]:
numbers.pct_change()

0         NaN
1    1.000000
2    0.500000
3    0.000000
4    0.333333
5    0.250000
dtype: float64

In [ ]:
numbers.mean()

3.0

In [ ]:
numbers.median()

3.0

In [ ]:
numbers.std()

1.5811388300841898

In [ ]:
numbers.max()

5.0

In [ ]:
numbers.min()

1.0

In [ ]:
animals = pd.Series(["koala", "cat", "dog"])
animals

0    koala
1      cat
2      dog
dtype: object

In [ ]:
animals.min()

'cat'

In [ ]:
animals.max()

'koala'

In [ ]:
numbers.describe()

count    5.000000
mean     3.000000
std      1.581139
min      1.000000
25%      2.000000
50%      3.000000
75%      4.000000
max      5.000000
dtype: float64

In [ ]:
numbers.sample(3)

2    3.0
1    2.0
0    1.0
dtype: float64

In [ ]:
authors = pd.Series(["Hemingway","Orwell","Dostoevsky","Fitzgerald","Orwell"])
authors.unique()

array(['Hemingway', 'Orwell', 'Dostoevsky', 'Fitzgerald'], dtype=object)

In [ ]:
authors.nunique()

4

In [ ]:
s1 = pd.Series(data = [5, np.nan, 15], index = ["A","B","C"])
s1

A     5.0
B     NaN
C    15.0
dtype: float64

In [ ]:
s1 + 3

A     8.0
B     NaN
C    18.0
dtype: float64

In [ ]:
s1.add(3)

A     8.0
B     NaN
C    18.0
dtype: float64

In [ ]:
s1 - 3

A     2.0
B     NaN
C    12.0
dtype: float64

In [ ]:
s1.sub(3)

A     2.0
B     NaN
C    12.0
dtype: float64

In [ ]:
s1.subtract(3)

A     2.0
B     NaN
C    12.0
dtype: float64

In [ ]:
s1 * 2

A    10.0
B     NaN
C    30.0
dtype: float64

In [ ]:
s1.mul(2)

A    10.0
B     NaN
C    30.0
dtype: float64

In [ ]:
s1.multiply(2)

A    10.0
B     NaN
C    30.0
dtype: float64

In [ ]:
s1/2

A    2.5
B    NaN
C    7.5
dtype: float64

In [ ]:
s1.div(2)

A    2.5
B    NaN
C    7.5
dtype: float64

In [ ]:
s1.divide(2)

A    2.5
B    NaN
C    7.5
dtype: float64

In [ ]:
s1//2

A    2.0
B    NaN
C    7.0
dtype: float64

In [ ]:
s1.floordiv(2)

A    2.0
B    NaN
C    7.0
dtype: float64

In [ ]:
s1 % 3

A    2.0
B    NaN
C    0.0
dtype: float64

In [ ]:
s1.mod(3)

A    2.0
B    NaN
C    0.0
dtype: float64

In [ ]:
s1 = pd.Series(data = [1,2,3], index = ["A","B","C"])
s2 = pd.Series(data = [4,5,6], index = ["A","B","C"])

In [ ]:
s1 + s2

A    5
B    7
C    9
dtype: int64

In [ ]:
s1 = pd.Series(data = [3,6,np.nan,12])
s2 = pd.Series(data = [2,6,np.nan,12])

In [ ]:
s1 + s2

0     5.0
1    12.0
2     NaN
3    24.0
dtype: float64

In [ ]:
s1 == s2

0    False
1     True
2    False
3     True
dtype: bool

In [ ]:
s1.eq(s2)

0    False
1     True
2    False
3     True
dtype: bool

In [ ]:
s1 != s2

0     True
1    False
2     True
3    False
dtype: bool

In [ ]:
s1.ne(s2)

0     True
1    False
2     True
3    False
dtype: bool

In [ ]:
cities = pd.Series(data = ["San Francisco","Los Angeles","Las Vegas", np.nan])
cities

0    San Francisco
1      Los Angeles
2        Las Vegas
3              NaN
dtype: object

In [ ]:
len(cities)

4

In [ ]:
type(cities)

pandas.core.series.Series

In [ ]:
list(cities)

['San Francisco', 'Los Angeles', 'Las Vegas', nan]

In [ ]:
dict(cities)

{0: 'San Francisco', 1: 'Los Angeles', 2: 'Las Vegas', 3: nan}

In [ ]:
"Las Vegas" in cities

False

In [ ]:
2 in cities

True

In [ ]:
"Las Vegas" in cities.values

True

In [ ]:
100 not in cities

True

In [ ]:
"Paris" in cities.values

False

In [ ]:
superheroes = ["Batman", "Superman", "Spiderman", "IronMan", "Capt.America","WonderWoman"]
strength_levels = (100,120,90,95,110,120)

In [ ]:
heroes = pd.Series(data = strength_levels, index = superheroes)

In [ ]:
heroes

Batman          100
Superman        120
Spiderman        90
IronMan          95
Capt.America    110
WonderWoman     120
dtype: int64

In [ ]:
heroes.head(2)

Batman      100
Superman    120
dtype: int64

In [ ]:
heroes.tail(4)

Spiderman        90
IronMan          95
Capt.America    110
WonderWoman     120
dtype: int64

In [ ]:
heroes.nunique()

5

In [ ]:
heroes.mean()

105.83333333333333

In [ ]:
heroes[heroes == heroes.max()]

Superman       120
WonderWoman    120
dtype: int64

In [ ]:
heroes.min()

90

In [ ]:
heroes * 2

Batman          200
Superman        240
Spiderman       180
IronMan         190
Capt.America    220
WonderWoman     240
dtype: int64

In [ ]:
dict(heroes)

{'Batman': 100,
 'Capt.America': 110,
 'IronMan': 95,
 'Spiderman': 90,
 'Superman': 120,
 'WonderWoman': 120}

# Numpy

In [ ]:
import numpy as np

In [ ]:
np.arange(3)

array([0, 1, 2])

In [ ]:
np.arange(2,6)

array([2, 3, 4, 5])

In [ ]:
np.arange(start=2,stop=6)

array([2, 3, 4, 5])

In [ ]:
np.arange(start=0,stop=101,step=10)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
tens = np.arange(start=0,stop=111,step=10)
tens

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110])

In [ ]:
tens.shape

(12,)

In [ ]:
tens.ndim

1

In [ ]:
tens.size

12

In [ ]:
tens.reshape(4,3)

array([[  0,  10,  20],
       [ 30,  40,  50],
       [ 60,  70,  80],
       [ 90, 100, 110]])

In [ ]:
tens.reshape(4,3)[1][0]

30

In [ ]:
tens.reshape(4,3).ndim

2

In [ ]:
tens.reshape(2,6)

array([[  0,  10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100, 110]])

In [ ]:
# tens.reshape(2,5) # Arroja error ValueError: cannot reshape array of size 12 into shape (2,5)

ValueError: ignored

In [ ]:
tens.reshape(2,3,2)

array([[[  0,  10],
        [ 20,  30],
        [ 40,  50]],

       [[ 60,  70],
        [ 80,  90],
        [100, 110]]])

In [ ]:
tens.reshape(2,3,2).ndim

3

In [ ]:
tens.reshape(2,-1)

array([[  0,  10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100, 110]])

In [ ]:
tens.reshape(2,-1,2)

array([[[  0,  10],
        [ 20,  30],
        [ 40,  50]],

       [[ 60,  70],
        [ 80,  90],
        [100, 110]]])

In [ ]:
np.random.randint(37)

21

In [ ]:
np.random.randint(1,10)

5

In [ ]:
np.random.randint(1,10,5)

array([3, 7, 1, 2, 1])

In [ ]:
np.random.randint(1,10,[5])

array([8, 8, 7, 6, 6])

In [ ]:
np.random.randint(1,10,[5,2])

array([[9, 9],
       [8, 2],
       [9, 6],
       [8, 2],
       [5, 6]])

In [ ]:
np.random.seed(123)
np.random.randint(1,10,[5,2])

array([[3, 3],
       [7, 2],
       [4, 7],
       [2, 1],
       [2, 1]])

In [ ]:
np.random.randn(10)

array([ 0.68007153, -1.00496715,  0.64021868,  1.37499063, -0.13044469,
       -0.24865585, -0.66964715, -0.01360389,  0.68620069, -0.8176683 ])

In [ ]:
np.random.randn(5,4)

array([[-1.34635756, -0.37574991, -1.37972498,  0.52321844],
       [-0.42668977, -1.75540184, -0.34860751, -0.19261499],
       [ 0.44913561, -0.14536354,  1.86872646, -0.51870385],
       [-0.06239855, -0.10291061, -0.28262838,  0.14242559],
       [ 0.5412313 ,  1.3400987 , -1.56925613, -0.51034287]])

In [ ]:
np.random.normal(1.67,0.05, 10)

array([1.64761143, 1.71689251, 1.65216685, 1.57524122, 1.67438652,
       1.66831554, 1.67898758, 1.61799186, 1.75595173, 1.65380701])